version: 1

formatters:
  simple:
    format: "%(asctime)s - %(levelname)s - %(name)s:%(lineno)d - %(message)s"

handlers:
  console_handler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple

loggers:
  src:
    level: DEBUG
  __main__:
    level: DEBUG

root:
  level: WARNING
  handlers: [console_handler]

disable_existing_loggers: False
